name = "trip-terminal-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
routes = [
  { pattern = "api.tripterminal.net/*", custom_domain = true }
]

[vars]
ALLOWED_ORIGIN = "https://tripterminal.net"
DAILY_REQUEST_CAP = "500"

[[kv_namespaces]]
binding = "RATE_STORE"
id = "cd74034c797241ad8df35728578c4996"
