name = "trip-terminal-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGIN = "https://brandonmparker.net"
DAILY_REQUEST_CAP = "500"

[[kv_namespaces]]
binding = "RATE_STORE"
id = "cd74034c797241ad8df35728578c4996"
